<?xml version="1.0" encoding="UTF-8"?>
  <testsuite name="Rest Api Test Suite" tests="2" failures="1" errors="0" time="63.89">
      <testcase name="REST API Test Suite - Single profile Running REST API Test Suite in fabric-test Starting fabric network" classname="Rest Api Test Suite" time="38.858296263"></testcase>
      <testcase name="REST API Test Suite - Single profile Running REST API Test Suite in fabric-test starting fabric network" classname="Rest Api Test Suite" time="25.030310748">
          <failure type="Failure">/home/atsushi/hyperledger/fabric-block-archiving-testenv/e2e-test/specs/apitest_test.go:47&#xA;Unexpected error:&#xA;    &lt;*exec.ExitError | 0xc0002c4ac0&gt;: {&#xA;        ProcessState: {&#xA;            pid: 19702,&#xA;            status: 256,&#xA;            rusage: {&#xA;                Utime: {Sec: 2, Usec: 251843},&#xA;                Stime: {Sec: 0, Usec: 234416},&#xA;                Maxrss: 105152,&#xA;                Ixrss: 0,&#xA;                Idrss: 0,&#xA;                Isrss: 0,&#xA;                Minflt: 22885,&#xA;                Majflt: 0,&#xA;                Nswap: 0,&#xA;                Inblock: 0,&#xA;                Oublock: 32,&#xA;                Msgsnd: 0,&#xA;                Msgrcv: 0,&#xA;                Nsignals: 0,&#xA;                Nvcsw: 538,&#xA;                Nivcsw: 957,&#xA;            },&#xA;        },&#xA;        Stderr: nil,&#xA;    }&#xA;    exit status 1&#xA;occurred&#xA;/home/atsushi/hyperledger/fabric-block-archiving-testenv/e2e-test/specs/apitest_test.go:77</failure>
          <system-out>�[1mSTEP�[0m: 0) Generating channel artifacts&#xA;�[1mSTEP�[0m: 1) Creating channel&#xA;�[1mSTEP�[0m: 2) Joining Peers to channel&#xA;�[1mSTEP�[0m: 3) Updating channel with anchor peers&#xA;�[1mSTEP�[0m: 4) Installing Chaincode on Peers&#xA;</system-out>
      </testcase>
  </testsuite>